// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { warning } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/node_modules/.pnpm/rc-util@5.44.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/rc-util';
import { SiteContext, type ISiteContext } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.6_@swc+helpers@0.5.15_@types+node@25.0.8_@types+react@18.3.27_es_ctsrt2kh6xjtv7fwqiwqchs62i/node_modules/dumi/dist/client/theme-api/context.js';
import { components } from '../meta/atoms';
import { locales } from '../locales/config';



const entryExports = {
};

// Static content
const pkg = {"name":"weave-docs"};
const historyType = "browser";
const hostname = undefined;
const themeConfig = {"logo":"/weave-dumi-pages/weave.svg","title":"Weave","footer":"Weave · OffscreenCanvas + Yoga + DisplayList","prefersColor":{"default":"light","switch":true},"nprogress":true,"lastUpdated":true,"name":"Weave","nav":[{"title":"指南","link":"/guide/getting-started"},{"title":"选型与对比","link":"/quick-comparison/selection"},{"title":"参考","link":"/reference/scene"},{"title":"示例","link":"/demos"},{"title":"子包","children":[{"title":"@jiujue/weave-types","link":"/types"},{"title":"@jiujue/weave-core","link":"/core"},{"title":"@jiujue/weave-displaylist","link":"/displaylist"},{"title":"@jiujue/weave-adapter-offscreen","link":"/adapter-offscreen"},{"title":"@jiujue/weave-adapter-node","link":"/adapter-node"},{"title":"@jiujue/weave-app","link":"/app"},{"title":"@jiujue/weave-react","link":"/react"}]}],"socialLinks":{}};
const _2_level_nav_available = true;

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(false);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  const context: ISiteContext = React.useMemo(() => {
    const ctx = {
      pkg,
      historyType,
      entryExports,
      demos: null,
      components,
      locales,
      loading,
      setLoading,
      hostname,
      themeConfig,
      _2_level_nav_available,
    };

    // Proxy do not warning since `Object.keys` will get nothing to loop
    Object.defineProperty(ctx, 'demos', {
      get: () => {
        warning(false, '`demos` return empty in latest version, please use `useDemo` instead.');
        return {};
      },
    });

    return ctx;
  }, [
    pkg,
    historyType,
    entryExports,
    components,
    locales,
    loading,
    setLoading,
    hostname,
    themeConfig,
    _2_level_nav_available,
  ]);

  return (
    <SiteContext.Provider value={context}>
      {outlet}
    </SiteContext.Provider>
  );
}
