// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/worker-rendered-business-report.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/worker-rendered-business-report.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/worker-rendered-batch-reports.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/worker-rendered-batch-reports.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/adapter-offscreen/index.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/adapter-offscreen/index.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/devtools-table-scroll.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/devtools-table-scroll.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/worker-rendered-image.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/worker-rendered-image.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/adapter-node/index.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/adapter-node/index.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/reference/devtools-protocol.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/reference/devtools-protocol.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/displaylist/index.md?type=frontmatter';
import { demoIndex as dmi7 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/displaylist/index.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/quick-comparison/selection.md?type=frontmatter';
import { demoIndex as dmi8 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/quick-comparison/selection.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/scroll-container-xy.md?type=frontmatter';
import { demoIndex as dmi9 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/scroll-container-xy.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/relative-container.md?type=frontmatter';
import { demoIndex as dmi10 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/relative-container.md?type=demo-index';
import { frontmatter as fm11, toc as t11 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/scroll-container-x.md?type=frontmatter';
import { demoIndex as dmi11 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/scroll-container-x.md?type=demo-index';
import { frontmatter as fm12, toc as t12 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/adapter-offscreen/index.md?type=frontmatter';
import { demoIndex as dmi12 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/adapter-offscreen/index.md?type=demo-index';
import { frontmatter as fm13, toc as t13 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/reference/context2dlike.md?type=frontmatter';
import { demoIndex as dmi13 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/reference/context2dlike.md?type=demo-index';
import { frontmatter as fm14, toc as t14 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/scroll-container.md?type=frontmatter';
import { demoIndex as dmi14 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/scroll-container.md?type=demo-index';
import { frontmatter as fm15, toc as t15 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/offscreen-worker.md?type=frontmatter';
import { demoIndex as dmi15 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/offscreen-worker.md?type=demo-index';
import { frontmatter as fm16, toc as t16 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/scroll-container.md?type=frontmatter';
import { demoIndex as dmi16 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/scroll-container.md?type=demo-index';
import { frontmatter as fm17, toc as t17 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/dynamic-patches.md?type=frontmatter';
import { demoIndex as dmi17 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/dynamic-patches.md?type=demo-index';
import { frontmatter as fm18, toc as t18 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/getting-started.md?type=frontmatter';
import { demoIndex as dmi18 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/getting-started.md?type=demo-index';
import { frontmatter as fm19, toc as t19 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/scene-from-jsx.md?type=frontmatter';
import { demoIndex as dmi19 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/scene-from-jsx.md?type=demo-index';
import { frontmatter as fm20, toc as t20 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/jsx-runtime-js.md?type=frontmatter';
import { demoIndex as dmi20 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/jsx-runtime-js.md?type=demo-index';
import { frontmatter as fm21, toc as t21 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/jsx-runtime-ts.md?type=frontmatter';
import { demoIndex as dmi21 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/jsx-runtime-ts.md?type=demo-index';
import { frontmatter as fm22, toc as t22 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/react/index.md?type=frontmatter';
import { demoIndex as dmi22 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/react/index.md?type=demo-index';
import { frontmatter as fm23, toc as t23 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/types/index.md?type=frontmatter';
import { demoIndex as dmi23 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/types/index.md?type=demo-index';
import { frontmatter as fm24, toc as t24 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/engine-replay.md?type=frontmatter';
import { demoIndex as dmi24 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/engine-replay.md?type=demo-index';
import { frontmatter as fm25, toc as t25 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/core/index.md?type=frontmatter';
import { demoIndex as dmi25 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/core/index.md?type=demo-index';
import { frontmatter as fm26, toc as t26 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/adapter-node/index.md?type=frontmatter';
import { demoIndex as dmi26 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/adapter-node/index.md?type=demo-index';
import { frontmatter as fm27, toc as t27 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/table-scroll.md?type=frontmatter';
import { demoIndex as dmi27 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/table-scroll.md?type=demo-index';
import { frontmatter as fm28, toc as t28 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/architecture.md?type=frontmatter';
import { demoIndex as dmi28 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/architecture.md?type=demo-index';
import { frontmatter as fm29, toc as t29 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/app/index.md?type=frontmatter';
import { demoIndex as dmi29 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/app/index.md?type=demo-index';
import { frontmatter as fm30, toc as t30 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/json-render.md?type=frontmatter';
import { demoIndex as dmi30 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/json-render.md?type=demo-index';
import { frontmatter as fm31, toc as t31 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/jsx-runtime.md?type=frontmatter';
import { demoIndex as dmi31 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/jsx-runtime.md?type=demo-index';
import { frontmatter as fm32, toc as t32 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/displaylist/index.md?type=frontmatter';
import { demoIndex as dmi32 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/displaylist/index.md?type=demo-index';
import { frontmatter as fm33, toc as t33 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/extension.md?type=frontmatter';
import { demoIndex as dmi33 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/extension.md?type=demo-index';
import { frontmatter as fm34, toc as t34 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/reference/patch.md?type=frontmatter';
import { demoIndex as dmi34 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/reference/patch.md?type=demo-index';
import { frontmatter as fm35, toc as t35 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/reference/scene.md?type=frontmatter';
import { demoIndex as dmi35 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/reference/scene.md?type=demo-index';
import { frontmatter as fm36, toc as t36 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/dataflow.md?type=frontmatter';
import { demoIndex as dmi36 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/dataflow.md?type=demo-index';
import { frontmatter as fm37, toc as t37 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/devtools.md?type=frontmatter';
import { demoIndex as dmi37 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/devtools.md?type=demo-index';
import { frontmatter as fm38, toc as t38 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/patches.md?type=frontmatter';
import { demoIndex as dmi38 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/patches.md?type=demo-index';
import { frontmatter as fm39, toc as t39 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/layout.md?type=frontmatter';
import { demoIndex as dmi39 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/layout.md?type=demo-index';
import { frontmatter as fm40, toc as t40 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/layout.md?type=frontmatter';
import { demoIndex as dmi40 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/layout.md?type=demo-index';
import { frontmatter as fm41, toc as t41 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/index.md?type=frontmatter';
import { demoIndex as dmi41 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/index.md?type=demo-index';
import { frontmatter as fm42, toc as t42 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/table.md?type=frontmatter';
import { demoIndex as dmi42 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/table.md?type=demo-index';
import { frontmatter as fm43, toc as t43 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/table.md?type=frontmatter';
import { demoIndex as dmi43 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/table.md?type=demo-index';
import { frontmatter as fm44, toc as t44 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/react/index.md?type=frontmatter';
import { demoIndex as dmi44 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/react/index.md?type=demo-index';
import { frontmatter as fm45, toc as t45 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/types/index.md?type=frontmatter';
import { demoIndex as dmi45 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/types/index.md?type=demo-index';
import { frontmatter as fm46, toc as t46 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/core/index.md?type=frontmatter';
import { demoIndex as dmi46 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/core/index.md?type=demo-index';
import { frontmatter as fm47, toc as t47 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/app/index.md?type=frontmatter';
import { demoIndex as dmi47 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/app/index.md?type=demo-index';
import { frontmatter as fm48, toc as t48 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/index.md?type=frontmatter';
import { demoIndex as dmi48 } from '/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/index.md?type=demo-index';

export const filesMeta = {
  'docs/demos/worker-rendered-business-report': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/worker-rendered-business-report.md?type=text'),
  },
  'docs/demos/worker-rendered-batch-reports': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/worker-rendered-batch-reports.md?type=text'),
  },
  'docs/packages/adapter-offscreen/index': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/adapter-offscreen/index.md?type=text'),
  },
  'docs/demos/devtools-table-scroll': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/devtools-table-scroll.md?type=text'),
  },
  'docs/demos/worker-rendered-image': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/worker-rendered-image.md?type=text'),
  },
  'docs/packages/adapter-node/index': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/adapter-node/index.md?type=text'),
  },
  'docs/reference/devtools-protocol': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/reference/devtools-protocol.md?type=text'),
  },
  'docs/packages/displaylist/index': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/displaylist/index.md?type=text'),
  },
  'docs/quick-comparison/selection': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/quick-comparison/selection.md?type=text'),
  },
  'docs/demos/scroll-container-xy': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/scroll-container-xy.md?type=text'),
  },
  'docs/demos/relative-container': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/relative-container.md?type=text'),
  },
  'docs/demos/scroll-container-x': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/scroll-container-x.md?type=text'),
  },
  'docs/adapter-offscreen/index': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/adapter-offscreen/index.md?type=text'),
  },
  'docs/reference/context2dlike': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/reference/context2dlike.md?type=text'),
  },
  'docs/demos/scroll-container': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/scroll-container.md?type=text'),
  },
  'docs/guide/offscreen-worker': {
    frontmatter: fm15,
    toc: t15,
    demoIndex: dmi15,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/offscreen-worker.md?type=text'),
  },
  'docs/guide/scroll-container': {
    frontmatter: fm16,
    toc: t16,
    demoIndex: dmi16,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/scroll-container.md?type=text'),
  },
  'docs/demos/dynamic-patches': {
    frontmatter: fm17,
    toc: t17,
    demoIndex: dmi17,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/dynamic-patches.md?type=text'),
  },
  'docs/guide/getting-started': {
    frontmatter: fm18,
    toc: t18,
    demoIndex: dmi18,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/getting-started.md?type=text'),
  },
  'docs/demos/scene-from-jsx': {
    frontmatter: fm19,
    toc: t19,
    demoIndex: dmi19,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/scene-from-jsx.md?type=text'),
  },
  'docs/guide/jsx-runtime-js': {
    frontmatter: fm20,
    toc: t20,
    demoIndex: dmi20,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/jsx-runtime-js.md?type=text'),
  },
  'docs/guide/jsx-runtime-ts': {
    frontmatter: fm21,
    toc: t21,
    demoIndex: dmi21,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/jsx-runtime-ts.md?type=text'),
  },
  'docs/packages/react/index': {
    frontmatter: fm22,
    toc: t22,
    demoIndex: dmi22,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/react/index.md?type=text'),
  },
  'docs/packages/types/index': {
    frontmatter: fm23,
    toc: t23,
    demoIndex: dmi23,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/types/index.md?type=text'),
  },
  'docs/demos/engine-replay': {
    frontmatter: fm24,
    toc: t24,
    demoIndex: dmi24,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/engine-replay.md?type=text'),
  },
  'docs/packages/core/index': {
    frontmatter: fm25,
    toc: t25,
    demoIndex: dmi25,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/core/index.md?type=text'),
  },
  'docs/adapter-node/index': {
    frontmatter: fm26,
    toc: t26,
    demoIndex: dmi26,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/adapter-node/index.md?type=text'),
  },
  'docs/demos/table-scroll': {
    frontmatter: fm27,
    toc: t27,
    demoIndex: dmi27,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/table-scroll.md?type=text'),
  },
  'docs/guide/architecture': {
    frontmatter: fm28,
    toc: t28,
    demoIndex: dmi28,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/architecture.md?type=text'),
  },
  'docs/packages/app/index': {
    frontmatter: fm29,
    toc: t29,
    demoIndex: dmi29,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/packages/app/index.md?type=text'),
  },
  'docs/demos/json-render': {
    frontmatter: fm30,
    toc: t30,
    demoIndex: dmi30,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/json-render.md?type=text'),
  },
  'docs/demos/jsx-runtime': {
    frontmatter: fm31,
    toc: t31,
    demoIndex: dmi31,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/jsx-runtime.md?type=text'),
  },
  'docs/displaylist/index': {
    frontmatter: fm32,
    toc: t32,
    demoIndex: dmi32,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/displaylist/index.md?type=text'),
  },
  'docs/guide/extension': {
    frontmatter: fm33,
    toc: t33,
    demoIndex: dmi33,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/extension.md?type=text'),
  },
  'docs/reference/patch': {
    frontmatter: fm34,
    toc: t34,
    demoIndex: dmi34,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/reference/patch.md?type=text'),
  },
  'docs/reference/scene': {
    frontmatter: fm35,
    toc: t35,
    demoIndex: dmi35,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/reference/scene.md?type=text'),
  },
  'docs/guide/dataflow': {
    frontmatter: fm36,
    toc: t36,
    demoIndex: dmi36,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/dataflow.md?type=text'),
  },
  'docs/guide/devtools': {
    frontmatter: fm37,
    toc: t37,
    demoIndex: dmi37,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/devtools.md?type=text'),
  },
  'docs/guide/patches': {
    frontmatter: fm38,
    toc: t38,
    demoIndex: dmi38,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/patches.md?type=text'),
  },
  'docs/demos/layout': {
    frontmatter: fm39,
    toc: t39,
    demoIndex: dmi39,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/layout.md?type=text'),
  },
  'docs/guide/layout': {
    frontmatter: fm40,
    toc: t40,
    demoIndex: dmi40,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/layout.md?type=text'),
  },
  'docs/demos/index': {
    frontmatter: fm41,
    toc: t41,
    demoIndex: dmi41,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/index.md?type=text'),
  },
  'docs/demos/table': {
    frontmatter: fm42,
    toc: t42,
    demoIndex: dmi42,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/demos/table.md?type=text'),
  },
  'docs/guide/table': {
    frontmatter: fm43,
    toc: t43,
    demoIndex: dmi43,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/guide/table.md?type=text'),
  },
  'docs/react/index': {
    frontmatter: fm44,
    toc: t44,
    demoIndex: dmi44,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/react/index.md?type=text'),
  },
  'docs/types/index': {
    frontmatter: fm45,
    toc: t45,
    demoIndex: dmi45,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/types/index.md?type=text'),
  },
  'docs/core/index': {
    frontmatter: fm46,
    toc: t46,
    demoIndex: dmi46,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/core/index.md?type=text'),
  },
  'docs/app/index': {
    frontmatter: fm47,
    toc: t47,
    demoIndex: dmi47,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/app/index.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm48,
    toc: t48,
    demoIndex: dmi48,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/jiujue/Documents/workspace/webWorkSpace/weave/apps/docs-dumi/docs/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
